export const tempPosiciones = [
    {
        pos: 1,
        equipo: 'Atlético Tucumán',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts: 25
    },
    {
        pos: 2,
        equipo: 'Gimnasia La Plata',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts: 21
    },
    {
        pos: 3,
        equipo: 'Argentinos Juniors',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:20
    },
    {
        pos: 4,
        equipo: 'Racing Club',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:19
    },
    {
        pos: 5,
        equipo: 'Godoy Cruz',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:18
    },
    {
        pos: 6,
        equipo: 'Platense',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:18
    },
    {
        pos: 7,
        equipo: 'Unión de Santa Fe',
        pj: 10,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:18
    },
    {
        pos: 8,
        equipo: 'Patronato',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:17
    },
    {
        pos: 9,
        equipo: 'Huracán',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:17
    },
    {
        pos: 10,
        equipo: 'San Lorenzo',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:16
    },
    {
        pos: 11,
        equipo: "Newell's Old Boys",
        pj:11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:16
    },
    {
        pos: 12,
        equipo: 'River Plate',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:15
    },
    {
        pos: 13,
        equipo: 'Boca Juniors',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:15
    },
    {
        pos: 14,
        equipo: 'Banfield',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:14
    },
    {
        pos: 15,
        equipo: ' Defensa y Justicia',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:14
    },
    {
        pos: 16,
        equipo: 'Sarmiento',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:14
    },
    {
        pos: 17,
        equipo: 'Rosario Central',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:14
    },
    {
        pos: 18,
        equipo: 'Tigre',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:13
    },
    {
        pos: 19,
        equipo: ' Arsenal de Sarandí',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:13
    },
    {
        pos: 20,
        equipo: 'Colón de Santa Fe',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:13
    },
    {
        pos: 21,
        equipo: 'Barracas Central',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:13
    },

    {
        pos: 22,
        equipo: 'Estudiantes de La Plata',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:12
    },
    {
        pos: 23,
        equipo: 'Independiente',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:11
    },
    {
        pos: 24,
        equipo: 'Central Córdoba SE',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:11
    },
    {
        pos: 25,
        equipo: 'Vélez Sarsfield',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:9
    },
    {
        pos: 26,
        equipo: 'Talleres de Córdoba',
        pj: 10,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:9
    },
    {
        pos: 27,
        equipo: ' Aldosivi',
        pj:11 ,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:8
    },
    {
        pos: 28,
        equipo: 'Lanús',
        pj: 11,
        g: 7,
        e: 4,
        p: 0,
        gf: 12,
        gc: 3,
        dg: '+9',
        pts:6
    }

]